#!/usr/bin/env python3
"""
Install files and services on the host device (Raspberry Pi Zero 2 W)
"""

import sys
import inspect
import shutil

from pathlib import Path

from install_config import *  # pylint: disable=unused-wildcard-import

from install_common import log, append_if_missing, chmod, chown_recursive, run_bash, write_file, install_pip_packages, install_apt_packages
from install_common import assert_root, assert_hostdevice


NEEDED_APT_PKGS: list[str] = [
    'git',
    'htop',
    'build-essential',
    'cmake',
    'python3',
    'python3-dev',
    'python3-pip',
    'iptables',
    'adb',
    'android-sdk-platform-tools-common',
    'iptables-persistent',
]

# NOTE: hosts maintenance center uses port 9090, and assumes superbird uses port 80
FORWARD_PORTS: dict[int, int] = {
    2022: 22,
    5900: 5900,
    5901: 5901,
    # 9222: 9222,
    9223: 9223,
    80: 80,
}

# #### Utility


def announce_myself():
    """Announce the start of this current function"""
    # NOTE this needs to be in the same file where it will be used, in order for the globals lookup to work
    frame = inspect.currentframe()
    if frame is None:
        return
    prev_frame = frame.f_back
    if prev_frame is None:
        return
    funcname = prev_frame.f_code.co_name
    funcdoc = globals()[funcname].__doc__
    log.info(f'#################### Running {funcname}() - {funcdoc}')


# #### Setup steps

def fix_enumeration():
    """Fix usb enumeration when connecting superbird in maskroom mode"""
    announce_myself()
    shutil.copy('./files/host/etc/udev/rules.d/70-carthing-maskrom-mode.rules', '/etc/udev/rules.d/70-carthing-maskrom-mode.rules')


def install_updater_service():
    """Install the updater service, used to orchestrate updates requested from the webui"""
    # NOTE do NOT start or stop the service here, just replace files and let the reboot take care of it
    #   otherwise, you will terminate the process which called this script to begin with!
    announce_myself()
    shutil.copy('./files/host/lib/systemd/system/kiosk-updater.service', '/lib/systemd/system/kiosk-updater.service')
    if Path('/kiosk-updater').is_dir():
        shutil.rmtree('/kiosk-updater')
    shutil.copytree('./files/host/kiosk-updater', '/kiosk-updater')
    run_bash('systemctl enable kiosk-updater')


def fix_ifnames():
    """Prevent systemd / udev from renaming usb network devices by mac address"""
    announce_myself()
    files = [
        '/lib/systemd/network/73-usb-net-by-mac.link',
        '/lib/udev/rules.d/73-usb-net-by-mac.rules',
    ]
    for file in files:
        filepath = Path(file)
        log.debug(f'Checking for file: {filepath.absolute()}')
        if filepath.is_file():
            log.debug(f'Removing file: {filepath.absolute()}')
            filepath.unlink()


def _forward_port(src: int, dest: int):
    """Forward a port from host to superbird, given source and dest"""
    log.info(f'Forwarding port from host:{src} -> superbird:{dest}')
    scr_fwd = f"""
    iptables -t nat -A PREROUTING -p tcp -i wlan0 --dport "{src}" -j DNAT --to-destination "{USBNET_PREFIX}.2:{dest}"
    iptables -A FORWARD -p tcp -d "{USBNET_PREFIX}.2" --dport "{dest}" -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
    """
    run_bash(scr_fwd)


def setup_forwarding_rules():
    """Enable ipv4 forwarding, and forward ports thru to superbird device"""
    announce_myself()
    append_if_missing(file='/etc/sysctl.conf', line="net.ipv4.ip_forward = 1")
    run_bash('sysctl -p')
    Path('/etc/iptables').mkdir(exist_ok=True)

    log.info("Clearing all iptables rules")
    scr_clear = """
    iptables -F
    iptables -X
    iptables -Z
    iptables -t nat -F
    iptables -t nat -X
    iptables -t mangle -F
    iptables -t mangle -X
    iptables -t raw -F
    iptables -t raw -X
    """
    run_bash(scr_clear)

    log.info("Rewriting iptables rules")
    scr_rules = f"""
    iptables -P FORWARD ACCEPT
    iptables -A POSTROUTING -t nat -j MASQUERADE -s "{USBNET_PREFIX}.0/24"
    """
    run_bash(scr_rules)

    log.info("Forwarding ports")
    for src, dest in FORWARD_PORTS.items():
        _forward_port(src, dest)

    log.info("Persisting rules to file")
    run_bash('iptables-save > /etc/iptables/rules.v4')


def setup_interfaces():
    """Setup network interfaces, particularly usb0"""
    announce_myself()
    Path('/etc/network/interfaces.d').mkdir(exist_ok=True)
    content = f"""
    # generated by install-host.py
    allow-hotplug usb0
    iface usb0 inet static
        address {USBNET_PREFIX}.1
        netmask 255.255.255.0
    """
    write_file('/etc/network/interfaces.d/usb0', content)


def setup_hosts():
    """Setup superbird in hosts file"""
    announce_myself()
    append_if_missing("/etc/hosts", f"{USBNET_PREFIX}.2  {HOST_NAME}")


def setup_sshkey():
    """Setup ssh key authentication between host & superbird"""
    announce_myself()

    Path(f"/home/{USER_NAME}/.ssh").mkdir(exist_ok=True)
    chown_recursive(f"/home/{USER_NAME}/.ssh", USER_NAME)

    write_file(f"/home/{USER_NAME}/.ssh/id_rsa", SSH_KEY_PRIVATE)
    write_file(f"/home/{USER_NAME}/.ssh/id_rsa.pub", SSH_KEY_PUBLIC)

    content = """
    Host superbird
        User superbird
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
    """
    write_file(f"/home/{USER_NAME}/.ssh/config", content)

    chown_recursive(f"/home/{USER_NAME}/.ssh", USER_NAME)
    chmod(f"/home/{USER_NAME}/.ssh/config", 600)
    chmod(f"/home/{USER_NAME}/.ssh/id_rsa", 600)
    chmod(f"/home/{USER_NAME}/.ssh/id_rsa.pub", 600)


# #### The whole process

def install_host():
    """Setup this host device"""
    announce_myself()

    install_apt_packages(NEEDED_APT_PKGS)
    install_pip_packages('./files/host/kiosk-updater/requirements.txt')

    fix_enumeration()
    fix_ifnames()

    setup_forwarding_rules()
    setup_interfaces()

    setup_hosts()
    setup_sshkey()

    install_updater_service()


# #### Entrypoint

if __name__ == '__main__':

    try:
        log.info('Installing on host')
        log.debug(f'Base path: {BASE_PATH}')

        assert_hostdevice()
        assert_root()

        install_host()
    except Exception as ex:
        log.exception(f'Unexpected exception in install-host.py:main(): {ex}')
        sys.exit(1)
    log.info('Done setting up host!')
    log.info('Need to reboot for all changes to take effect')
